### ISSUE TITLE
React Native 0.71 support

### ISSUE THREAD

**Issue by alpha0010** [react-native-progress-view/progress-view#109]
Attempting `pod install` on RN 0.71, I get the error:
```
[!] Unable to find a specification for `React-RCTFabric` depended upon by `react-native-progress-view/fabric`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

Trying the recommended `pod repo update` and `pod install --repo-update` do not resolve the issue.

Library version: `1.4.0-beta.0`, hermes, old architecture.

**Comment by alpha0010** [comment]
Downgrading to `1.3.2` works fine.  Looks like the confusing point is the `latest` tag in npm points to the beta release, instead of `1.3.2` (which appears to be the intended stable).

**Comment by matiaskorhonen** [comment]
The problem seems to be the [Fabric check in the `podspec`](https://github.com/react-native-progress-view/progress-view/blob/c4027338102bf280e643cd037d85e7cade5d043a/react-native-progress-view.podspec#L3):

Instead of

```ruby
fabric_enabled = ENV['RCT_NEW_ARCH_ENABLED']
```

It should be:

```ruby
fabric_enabled = ENV['RCT_NEW_ARCH_ENABLED'] == '1'
```

When Fabric is disabled, `RCT_NEW_ARCH_ENABLED` is set to `'0'` which is truthy in Ruby.
